language: node_js

cache:
  directories:
    - "node_modules"
  yarn: true

node_js:
  - "8"

script:
  - npm test

branches:
  only:
  - develop

notifications:
  slack: guneysu:g4dUCQCfxQ4tHZziwDMOlU7k

before_deploy:
  - npm run build

deploy:
  on: develop
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: guneysu.portal.surge.sh  
