language: node_js

cache:
  directories:
    - "node_modules"
  yarn: true

node_js:
  - "8"

script:
  - echo "OK" || npm test

branches:
  only:
  - develop

notifications:
  slack: guneysu:g4dUCQCfxQ4tHZziwDMOlU7k

before_deploy:
  - npm run build

deploy:
  - provider: surge
    on: develop
    skip_cleanup: true
    project: ./dist/
    domain: guneysu-portal.surge.sh  

  - provider: surge
    on: master
    skip_cleanup: true
    project: ./dist/
    domain: guneysus.surge.sh  
